version: 2
references:
  build_config: &build_config
    working_directory: ~/ci-images
    docker:
      - image: docker:18.03-git

jobs:
  build_and_push_image_to_quay:
    <<: *build_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: quay.io docker login
          working_directory: ~/ci-images/go/1.11.1
          command: docker login quay.io -u "$QUAY_IO_USERNAME" -p "$QUAY_IO_PASSWORD"
      - run:
          name: docker build
          working_directory: ~/ci-images/go/1.11.1
          command: |
            docker build -t $GO_1.11.1_REPOSITORY .
      - run:
          name: quay.io docker push
          working_directory: ~/ci-images/go/1.11.1
          command: |
            docker tag $GO_1.11.1_REPOSITORY quay.io/gunosy/$GO_1.11.1_REPOSITORY:latest
            docker push quay.io/gunosy/$GO_1.11.1_REPOSITORY:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:     
      - build_and_push_image_to_quay:
          branches:
            only:
              - master
